- name: Setup docker
  ansible.builtin.include_tasks: "setup-{{ ansible_os_family }}.yml"

- name: Configure docker daemon
  when:
  - docker_daemon_options.keys()
  - docker_daemon_options.keys() | length > 0
  ansible.builtin.include_tasks: config.yml

- name: Ensure docker compose plugin backwards compatibility
  when:
  - docker_compose_compatibility_v2
  - docker_compose_compatibility_v2 | bool
  ansible.builtin.file:
    src: /usr/libexec/docker/cli-plugins/docker-compose
    dest: /usr/bin/docker-compose
    owner: root
    group: root
    state: link

- name: Ensure docker system state
  ansible.builtin.systemd_service:
    name: docker
    state: "{{ docker_systemd_state }}"
    enabled: "{{ docker_systemd_enabled }}"

- name: Setup docker users
  when: >
    docker_admin_users and
    docker_admin_users | length
  ansible.builtin.include_tasks: users.yml
