- name: Remove deprecated docker packages
  ansible.builtin.apt:
    name: "{{ docker_deprecated_packages }}"
    state: absent

- name: Install docker dependencies
  ansible.builtin.apt:
    name: "{{ docker_requirements }}"
    state: present

- name: Setup docker repository key
  ansible.builtin.get_url:
    url: "{{ docker_apt_gpg_key }}"
    dest: /etc/apt/trusted.gpg.d/docker.asc
    mode: 0644

- name: Setup docker repository
  ansible.builtin.apt_repository:
    repo: "{{ docker_apt_repository }}"
    state: present
    filename: docker
    update_cache: true

- name: Install docker
  ansible.builtin.apt:
    name: "{{ docker_packages }}"
    state: present
