- name: Converge
  hosts: all
  pre_tasks:
  - name: Update Cache (Debian)
    when: ansible_os_family == 'Debian'
    ansible.builtin.apt:
      update_cache: true
      cache_valid_time: 600

  roles:
  - dudecalledbro.docker
